Feature/solution
BullSprite/mat-model pull request #10
Opened 2021-09-08 14:50 UTC by NatsukiPrayer

Запилил солюшн, расхождение в тестовом варианте в пятом знаке

2021-09-08 15:04 UTC, BullSprite requested changes

2021-09-08 15:04 UTC, BullSprite commented on solution.py
> +        if AB.len()*HB.len()*AB.to_vector().cos_angle_between(HB.to_vector()) > 0:
Вынеси в отдельную функцию, код повторяется, только переменные меняются

2021-09-08 15:04 UTC, BullSprite commented on solution.py
> +        integ += height*(log(abs((1+tan(amax/2))/(1-tan(amax/2))))-log(abs((1+tan(amin/2))/(1-tan(amin/2)))))
Наверное тоже лучше сделать отдельной все сделать отдельной функцией и в конце результаты всех треугольников посчитать

2021-09-08 15:06 UTC, NatsukiPrayer commented on solution.py
> +        if AB.len()*HB.len()*AB.to_vector().cos_angle_between(HB.to_vector()) > 0:
Сделаю к вечеру

2021-09-08 15:06 UTC, NatsukiPrayer commented on solution.py
> +        integ += height*(log(abs((1+tan(amax/2))/(1-tan(amax/2))))-log(abs((1+tan(amin/2))/(1-tan(amin/2)))))
Принято

2021-09-08 15:16 UTC, BullSprite commented on solution.py
> +        integ += height*(log(abs((1+tan(amax/2))/(1-tan(amax/2))))-log(abs((1+tan(amin/2))/(1-tan(amin/2)))))
Типо return sum(Integral(line.start, line.end, op) for line in Lines)

2021-09-10 15:26 UTC, BullSprite requested changes

2021-09-10 15:26 UTC, BullSprite commented on solution.py
> +    integ = 0
Зачем?

2021-09-10 15:26 UTC, BullSprite commented on solution.py
> +    op = Point(point_O, name='O')
Зачем?

2021-09-10 15:26 UTC, BullSprite commented on solution.py
> +    return (height * (log(abs((1 + tan(amax / 2)) / (1 - tan(amax / 2)))) - log(
Опять можно оформить функцию

2021-09-10 16:54 UTC, BullSprite approved these changes

2021-09-10 16:54 UTC, merged